-- ---------------------------------------------------------------------------
-- Monetization dashboard storage.
--
-- KaliNova is not monetised. Everything in this file creates *storage* and
-- *seeding defaults*; nothing switches advertising on. Every new feature below
-- starts empty or disabled, exactly like ad_settings / ad_placements did.
--
-- New tables:
--   affiliate_links          affiliate destinations an editor manages centrally
--   affiliate_clicks         anonymized redirect log (no raw IPs, no sessions)
--   sponsored_campaigns      commercial relationship attached to one article
--   direct_ads               banner campaigns sold directly to advertisers
--   direct_ad_events         impressions + clicks generated by the public site
--   newsletter_subscribers   one row per email, status transitions in place
--   monetization_disclosures site-wide disclosure texts (editable in admin)
--   monetization_audit_logs  every admin monetization action, secrets excluded
--
-- Plus additive columns:
--   articles.ads_enabled          NULL = follow the category default
--   categories.default_*          monetization defaults a new article inherits
--
-- Design notes (mirroring the ad_placements migration):
--   * every statement is guarded, so re-running is a no-op
--   * only additive: no existing table is dropped, rewritten or re-seeded
--   * URLs are stored only as absolute http(s) values (database CHECK doubles
--     the application validation)
--   * no publisher id, API key or email-provider secret lives here
--   * subscriber emails are stored lowercased and unique; the public API never
--     returns them, and anonymised event tables store a hash, not the client IP
-- ---------------------------------------------------------------------------

-- --- helper: honest updated_at ---------------------------------------------
-- One function reused by every new table that carries an updated_at column.
CREATE OR REPLACE FUNCTION kalinova_touch_monetization_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- --- affiliate_links --------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'affiliate_links'
    ) THEN
        CREATE TABLE affiliate_links (
            id                SERIAL PRIMARY KEY,

            -- Display name and optional network label (e.g. "Amazon Associates").
            name              VARCHAR(120) NOT NULL,
            network           VARCHAR(80) NOT NULL DEFAULT '',

            -- Public link the visitor reaches through /go/<slug>. Absolute
            -- http(s) only; anything else the application rejects up front.
            destination_url   TEXT NOT NULL,
            tracking_url      TEXT NOT NULL DEFAULT '',

            -- Short disclosure shown next to the link; the site-wide affiliate
            -- disclosure is appended below it. Empty means "use the default".
            disclosure_text   TEXT NOT NULL DEFAULT '',

            -- Stable redirect slug: /go/<slug>. Unique so a redirect cannot
            -- dangle on a suffix later.
            slug              VARCHAR(80) NOT NULL UNIQUE,

            -- Optional attachment. Both may be set; either may be null.
            article_id        INTEGER REFERENCES articles(id) ON DELETE SET NULL,
            category_id       INTEGER REFERENCES categories(id) ON DELETE SET NULL,

            -- 'active' links are forwarded; 'paused' links answer 410 so a
            -- broken programme never silently drops the reader.
            status            VARCHAR(20) NOT NULL DEFAULT 'active',

            position          INTEGER NOT NULL DEFAULT 0,

            created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT affiliate_links_status_allowed CHECK (status IN ('active', 'paused')),
            CONSTRAINT affiliate_links_destination_url CHECK (
                destination_url ~ '^https?://[^\s<>]+$'
            ),
            CONSTRAINT affiliate_links_tracking_url CHECK (
                tracking_url = '' OR tracking_url ~ '^https?://[^\s<>]+$'
            ),
            CONSTRAINT affiliate_links_slug_format CHECK (
                slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'
            )
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_affiliate_links_status ON affiliate_links (status);
CREATE INDEX IF NOT EXISTS idx_affiliate_links_article ON affiliate_links (article_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_links_category ON affiliate_links (category_id);

DROP TRIGGER IF EXISTS affiliate_links_touch_updated_at ON affiliate_links;
CREATE TRIGGER affiliate_links_touch_updated_at
    BEFORE UPDATE ON affiliate_links
    FOR EACH ROW
    EXECUTE FUNCTION kalinova_touch_monetization_updated_at();

-- --- affiliate_clicks -------------------------------------------------------
-- The redirect log. Privacy rule: no raw IP address and no persistent visitor
-- id are stored. ip_hash is an HMAC of the client address derived with a server
-- secret, used only to drop obvious repeat/automated clicks; device is folded
-- from the User-Agent, and only the referrer host is kept.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'affiliate_clicks'
    ) THEN
        CREATE TABLE affiliate_clicks (
            id             BIGSERIAL PRIMARY KEY,
            affiliate_id   INTEGER NOT NULL REFERENCES affiliate_links(id) ON DELETE CASCADE,
            article_id     INTEGER REFERENCES articles(id) ON DELETE SET NULL,

            created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            referrer       VARCHAR(300) NOT NULL DEFAULT '',
            device         VARCHAR(16)  NOT NULL DEFAULT '',
            ip_hash        VARCHAR(64)  NOT NULL DEFAULT '',
            ua_snippet     VARCHAR(128) NOT NULL DEFAULT ''
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate_time
    ON affiliate_clicks (affiliate_id, created_at);
CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_created_at
    ON affiliate_clicks (created_at);

-- --- sponsored_campaigns ----------------------------------------------------
-- One article, one campaign. A published article with a non-draft campaign
-- renders a visible label and disclosure on the public article page.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'sponsored_campaigns'
    ) THEN
        CREATE TABLE sponsored_campaigns (
            id             SERIAL PRIMARY KEY,

            -- Exactly one campaign per article; assigning a second replaces the
            -- first (the application upserts on article_id).
            article_id     INTEGER NOT NULL UNIQUE REFERENCES articles(id) ON DELETE CASCADE,

            sponsor_name   VARCHAR(160) NOT NULL,
            sponsor_url    TEXT NOT NULL DEFAULT '',

            -- 'Sponsored' or 'Advertisement' — the badge a reader sees.
            label          VARCHAR(20) NOT NULL DEFAULT 'Sponsored',

            disclosure     TEXT NOT NULL DEFAULT '',

            start_at       TIMESTAMP WITH TIME ZONE,
            end_at         TIMESTAMP WITH TIME ZONE,

            status         VARCHAR(20) NOT NULL DEFAULT 'draft',

            created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT sponsored_campaigns_status_allowed
                CHECK (status IN ('draft', 'active', 'paused', 'ended')),
            CONSTRAINT sponsored_campaigns_label_allowed
                CHECK (label IN ('Sponsored', 'Advertisement')),
            CONSTRAINT sponsored_campaigns_sponsor_url CHECK (
                sponsor_url = '' OR sponsor_url ~ '^https?://[^\s<>]+$'
            )
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_sponsored_campaigns_status ON sponsored_campaigns (status);

DROP TRIGGER IF EXISTS sponsored_campaigns_touch_updated_at ON sponsored_campaigns;
CREATE TRIGGER sponsored_campaigns_touch_updated_at
    BEFORE UPDATE ON sponsored_campaigns
    FOR EACH ROW
    EXECUTE FUNCTION kalinova_touch_monetization_updated_at();

-- --- direct_ads -------------------------------------------------------------
-- Banner campaigns sold to advertisers. Unlike ad_placements (step 10), this
-- is a campaign table: it carries the advertiser, artwork URL, date window and
-- an explicit priority, and the public renderer derives 'active' from the
-- stored status *and* the date range.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'direct_ads'
    ) THEN
        CREATE TABLE direct_ads (
            id                SERIAL PRIMARY KEY,

            name              VARCHAR(120) NOT NULL,
            advertiser_name   VARCHAR(120) NOT NULL DEFAULT '',

            image_url         TEXT NOT NULL,
            image_alt         VARCHAR(300) NOT NULL DEFAULT '',
            destination_url   TEXT NOT NULL,

            placement         VARCHAR(40) NOT NULL,
            start_date        DATE,
            end_date          DATE,

            status            VARCHAR(20) NOT NULL DEFAULT 'draft',
            priority          INTEGER NOT NULL DEFAULT 100,
            campaign_notes    TEXT NOT NULL DEFAULT '',

            -- Denormalised counters, maintained by the public event endpoints
            -- inside the same transaction that records the event.
            impression_count  INTEGER NOT NULL DEFAULT 0,
            click_count       INTEGER NOT NULL DEFAULT 0,

            created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT direct_ads_status_allowed
                CHECK (status IN ('draft', 'scheduled', 'active', 'paused', 'expired')),
            CONSTRAINT direct_ads_placement_allowed
                CHECK (placement IN (
                    'homepage_top', 'homepage_middle', 'article_top', 'article_middle',
                    'article_bottom', 'sidebar', 'category_top', 'footer'
                )),
            CONSTRAINT direct_ads_image_url CHECK (image_url ~ '^https?://[^\s<>]+$'),
            CONSTRAINT direct_ads_destination_url CHECK (destination_url ~ '^https?://[^\s<>]+$'),
            CONSTRAINT direct_ads_date_window CHECK (
                start_date IS NULL OR end_date IS NULL OR end_date >= start_date
            ),
            CONSTRAINT direct_ads_priority_sane CHECK (priority BETWEEN 1 AND 1000)
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_direct_ads_placement_status
    ON direct_ads (placement, status, start_date, end_date);

DROP TRIGGER IF EXISTS direct_ads_touch_updated_at ON direct_ads;
CREATE TRIGGER direct_ads_touch_updated_at
    BEFORE UPDATE ON direct_ads
    FOR EACH ROW
    EXECUTE FUNCTION kalinova_touch_monetization_updated_at();

-- --- direct_ad_events -------------------------------------------------------
-- Impressions and clicks generated by the public site. Only anonymised data is
-- kept (see affiliate_clicks for the privacy rules); an obvious automated run
-- is dropped by the application layer, which also rate-limits both endpoints.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'direct_ad_events'
    ) THEN
        CREATE TABLE direct_ad_events (
            id           BIGSERIAL PRIMARY KEY,
            ad_id        INTEGER NOT NULL REFERENCES direct_ads(id) ON DELETE CASCADE,
            event_type   VARCHAR(16) NOT NULL,

            created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            referrer     VARCHAR(300) NOT NULL DEFAULT '',
            device       VARCHAR(16)  NOT NULL DEFAULT '',
            ip_hash      VARCHAR(64)  NOT NULL DEFAULT '',
            ua_snippet   VARCHAR(128) NOT NULL DEFAULT '',

            CONSTRAINT direct_ad_events_type_allowed CHECK (event_type IN ('impression', 'click'))
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_direct_ad_events_ad_time
    ON direct_ad_events (ad_id, event_type, created_at);
CREATE INDEX IF NOT EXISTS idx_direct_ad_events_created_at
    ON direct_ad_events (created_at);

-- --- newsletter_subscribers -------------------------------------------------
-- One row per subscribed email; re-subscribing reactivates the row rather than
-- creating a second one. Emails are stored lowercased. The unsubscribe token is
-- a random value issued by the application (never derived from the email).
-- status: 'pending' only when a double-opt-in provider is configured; the site
-- ships with no email provider, so subscriptions start 'subscribed'.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'newsletter_subscribers'
    ) THEN
        CREATE TABLE newsletter_subscribers (
            id                SERIAL PRIMARY KEY,

            email             VARCHAR(254) NOT NULL UNIQUE,
            name              VARCHAR(120) NOT NULL DEFAULT '',
            status            VARCHAR(20) NOT NULL DEFAULT 'subscribed',
            token             VARCHAR(64) NOT NULL UNIQUE,
            source            VARCHAR(20) NOT NULL DEFAULT 'site',

            subscribed_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            unsubscribed_at   TIMESTAMP WITH TIME ZONE,

            CONSTRAINT newsletter_subscribers_status_allowed
                CHECK (status IN ('subscribed', 'pending', 'unsubscribed')),
            CONSTRAINT newsletter_subscribers_email_lowercase CHECK (email = lower(email)),
            CONSTRAINT newsletter_subscribers_email_shape CHECK (
                email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'
            ),
            CONSTRAINT newsletter_subscribers_token_shape CHECK (
                token ~ '^[a-f0-9]{64}$'
            )
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_newsletter_subscribers_status ON newsletter_subscribers (status);

-- --- monetization_disclosures -----------------------------------------------
-- Singleton, like ad_settings. The texts are editorial copy the admin edits on
-- the Disclosures screen; they are plain language, not legal guarantees, and
-- are rendered on the pages that need them.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'monetization_disclosures'
    ) THEN
        CREATE TABLE monetization_disclosures (
            id                     SMALLINT PRIMARY KEY DEFAULT 1,

            affiliate_disclosure   TEXT NOT NULL DEFAULT
                'Some links on this page are affiliate links. If you make a purchase through them, KaliNova may earn a commission at no extra cost to you.',

            sponsored_disclosure   TEXT NOT NULL DEFAULT
                'This article was produced in partnership with a sponsor. The sponsor did not control the reporting or the final text.' ,

            advertising_disclosure TEXT NOT NULL DEFAULT
                'This page contains advertisements sold and placed by KaliNova. Advertisers do not influence editorial content.',

            privacy_notice         TEXT NOT NULL DEFAULT
                'KaliNova shows advertising only with your consent. See the privacy policy for how advertising data is handled.',

            updated_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

            CONSTRAINT monetization_disclosures_singleton CHECK (id = 1)
        );
    END IF;
END $$;

INSERT INTO monetization_disclosures (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- --- monetization_audit_logs ------------------------------------------------
-- Every admin monetization action worth remembering. details is a JSONB object;
-- the application sanitises it before writing, so a password or API key never
-- reaches this table.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = 'monetization_audit_logs'
    ) THEN
        CREATE TABLE monetization_audit_logs (
            id            BIGSERIAL PRIMARY KEY,
            admin_id      INTEGER REFERENCES users(id) ON DELETE SET NULL,

            action        VARCHAR(80) NOT NULL,
            entity_type   VARCHAR(40) NOT NULL DEFAULT '',
            entity_id     INTEGER,
            details       JSONB NOT NULL DEFAULT '{}',

            created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_monetization_audit_logs_created
    ON monetization_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_monetization_audit_logs_admin
    ON monetization_audit_logs (admin_id, created_at DESC);

-- --- articles: per-article ad override --------------------------------------
-- NULL means "follow the category default" (added below). An explicit true/false
-- set by the editor overrides it for that one article.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'articles'
          AND column_name = 'ads_enabled'
    ) THEN
        ALTER TABLE articles
            ADD COLUMN ads_enabled BOOLEAN;
    END IF;
END $$;

-- --- categories: monetization defaults --------------------------------------
-- New articles inherit these until the editor picks an override on the article.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'categories'
          AND column_name = 'default_ads_enabled'
    ) THEN
        ALTER TABLE categories
            ADD COLUMN default_ads_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN default_affiliate_enabled BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN default_direct_ads_enabled BOOLEAN NOT NULL DEFAULT TRUE;
    END IF;
END $$;